Repository KOBOT-13/2024OpenSW-FRONT, pull requests merged in 2024-08, with the labels that each got.

#70 Feat: 토큰 자동 갱신 기능 구현
  osskobot/src/App.js
  osskobot/src/components/CharProfile/CharProfile.js
  osskobot/src/components/CommentBoard/CommentBoard.js
  osskobot/src/components/Modal/BookRequestModal.js
  osskobot/src/components/Modal/CharIntroModal.js
  osskobot/src/components/ProtectedRoute/LoginProtectedRoute.js
  osskobot/src/components/ProtectedRoute/ProtectedRoute.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Join.js
  osskobot/src/screens/Login.js
  osskobot/src/screens/Logout.js
  osskobot/src/services/axiosConfig.js
  osskobot/src/services/refreshToken.js
Labels: enhancement

#74 Feat: 채팅 끝내기 버튼, 웹이름 누르면 채팅 끝내기 구현
  osskobot/src/components/ChatMsg/EndChat.js
  osskobot/src/components/Header/Header.js
  osskobot/src/screens/Chat.js
Labels: enhancement

#76 Feat: 이메일, 닉네임 중복 확인 기능 구현
  osskobot/src/screens/Join.js
  osskobot/src/screens/Join.module.css
Labels: enhancement

#79 Feat: 독후감 api 연결
  osskobot/src/forms/reportForm1.js
  osskobot/src/forms/reportForm2.js
  osskobot/src/forms/reportForm3.js
  osskobot/src/screens/BookReport.js
Labels: enhancement

#78 Refactor: axios 코드 리팩토링
  osskobot/src/components/ChatMsg/EndChat.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/Chat.js
  osskobot/src/screens/ChatCharChoose.js
Labels: enhancement

#82 Feat: 도서 신청하기 로직 수정
  osskobot/src/components/ProtectedRoute/ProtectedRoute.js
  osskobot/src/screens/BookReport.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Login.js
  osskobot/src/services/axiosConfig.js
  osskobot/src/services/refreshToken.js
Labels: enhancement

#85 Feat: 프로필 수정 api 연결
  osskobot/src/components/Modal/ProfileModifyModal.js
  osskobot/src/components/Modal/ProfileModifyModal.module.css
  osskobot/src/screens/Mypage.js
Labels: enhancement

#86 Feat: 등장인물 소개 api 연결
  osskobot/src/components/CharProfile/CharProfile.js
  osskobot/src/components/CharProfile/CharProfile.module.css
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookClick.module.css
Labels: enhancement

#89 Feat: 이전 대화 마이페이지 구현
  osskobot/src/components/PreviousChat/PreviousChat.js
  osskobot/src/screens/Chat.js
  osskobot/src/screens/Mypage.js
Labels: enhancement

#91 Feat: 대화 끝내기 api 연결
  osskobot/src/App.js
  osskobot/src/components/ChatMsg/ConversationContext.js
  osskobot/src/components/ChatMsg/EndChat.js
  osskobot/src/components/Header/Header.js
  osskobot/src/screens/Chat.js
Labels: enhancement

#98 Feat: 로그인 전 비밀번호 변경 구현
  osskobot/src/App.js
  osskobot/src/screens/Find.js
Labels: enhancement

#99 Refactor: api 호출 줄이기 위해 코드 수정
  osskobot/src/components/PreviousChat/PreviousChat.js
  osskobot/src/screens/Mypage.js
Labels: enhancement

#101 Feat: 로그인 후 비밀번호 변경 구현
  osskobot/src/components/Modal/ProfileModifyModal.js
  osskobot/src/components/Modal/ProfileModifyModal.module.css
  osskobot/src/screens/Login.js
Labels: enhancement

#106 Feat: 마이페이지 '내가 읽은 책' 구현
  osskobot/src/components/BookReport/BookReportInfo.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookReport.js
  osskobot/src/screens/Chat.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Login.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/Quiz.js
  osskobot/src/services/postReadBook.js
Labels: enhancement

#105 Feat: 내가 쓴 글 마이페이지 구현
  osskobot/src/components/MyComments/MyComments.js
  osskobot/src/screens/Mypage.js
Labels: enhancement

#110 Fix: 로그아웃 모달 버그 수정
  osskobot/src/components/Modal/CheckModal.js
  osskobot/src/screens/BookClick.js
Labels: bug

#112 Feat: Header CSS 작업
  osskobot/public/Logo192.svg
  osskobot/public/Logo512.svg
  osskobot/public/favicon.ico
  osskobot/public/favicon.svg
  osskobot/public/index.html
  osskobot/public/logo192.png
  osskobot/public/logo512.png
  osskobot/public/manifest.json
  osskobot/src/App.css
  osskobot/src/assets/AiLogo.js
  osskobot/src/assets/Arrow.svg
  osskobot/src/assets/Logo.svg
  osskobot/src/assets/fonts/Pretendard-Bold.otf
  osskobot/src/assets/fonts/Pretendard-Medium.otf
  osskobot/src/assets/fonts/Pretendard-Regular.otf
  osskobot/src/assets/fonts/Pretendard-SemiBold.otf
  osskobot/src/assets/search.svg
  osskobot/src/components/Header/Header.js
  osskobot/src/screens/ServiceInfo.js
Labels: enhancement

#114 Feat: Home CSS 작업
  osskobot/src/components/Book/Book.js
  osskobot/src/components/CustomButton/CategoryBtn.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Header/Header.module.css
  osskobot/src/components/Header/SubHeader.js
  osskobot/src/components/SelectBox/SelectBox.js
  osskobot/src/screens/Home.js
Labels: enhancement

#116 Feat: Service Information 스크린 CSS 작업
  osskobot/src/components/Profile/Profile.module.css
  osskobot/src/screens/Home.js
  osskobot/src/screens/ServiceInfo.js
Labels: enhancement

#118 Feat: 책 소개 스크린 CSS 작업
  osskobot/public/manifest.json
  osskobot/src/assets/Logo320.svg
  osskobot/src/assets/banner.jpg
  osskobot/src/assets/quiz.svg
  osskobot/src/assets/report.svg
  osskobot/src/assets/talk.svg
  osskobot/src/components/CharProfile/CharProfile.module.css
  osskobot/src/components/CommentBoard/CommentBoard.js
  osskobot/src/components/CommentBoard/CommentBoard.module.css
  osskobot/src/components/CommentBoard/CommentBoardStyled.js
  osskobot/src/components/CustomButton/BookClickBtn.js
  osskobot/src/components/CustomButton/BottomBorderBtn.js
  osskobot/src/components/CustomButton/CategoryBtn.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Header/SubHeader.js
  osskobot/src/components/Modal/CheckModal.js
  osskobot/src/components/SelectBox/SelectBox.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookClick.module.css
  osskobot/src/screens/BookClickStyled.js
  osskobot/src/screens/BookReport.module.css
  osskobot/src/screens/Home.js
  osskobot/src/screens/ServiceInfo.module.css
Labels: enhancement

#120 Feat: Footer 구현
  osskobot/src/components/CommentBoard/CommentBoard.js
  osskobot/src/components/CommentBoard/CommentBoard.module.css
  osskobot/src/components/CommentBoard/CommentBoardStyled.js
  osskobot/src/components/Modal/CheckModal.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookClick.module.css
  osskobot/src/screens/BookClick.styled.js
Labels: enhancement

#122 Fix: 푸쉬 실수 정상화
  osskobot/src/App.js
  osskobot/src/assets/instargram.svg
  osskobot/src/assets/youtube.svg
  osskobot/src/components/Footer/Footer.js
Labels: bug, enhancement

#124 Feat: 캐릭터 선택 스크린 CSS 작업
  osskobot/src/components/CharProfile/CharProfile.js
  osskobot/src/components/CharProfile/CharProfile.module.css
  osskobot/src/components/Header/ChatHeader.js
  osskobot/src/components/Modal/CharIntroModal.js
  osskobot/src/components/Modal/CharIntroModal.module.css
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/ChatCharChoose.js
Labels: enhancement

#126 Feat: 독후감 작성하기 CSS 작업
  osskobot/src/components/CustomButton/BookClickBtn.js
  osskobot/src/components/Header/ChatHeader.js
  osskobot/src/components/SelectBox/SelectBox.js
  osskobot/src/screens/BookReport.js
  osskobot/src/screens/BookReportStyled.js
  osskobot/src/screens/ChatCharChoose.js
  osskobot/src/screens/Home.js
Labels: enhancement

#128 Feat: 퀴즈 스크린 CSS 작업
  osskobot/src/assets/ChatImage.png
  osskobot/src/assets/Correct.png
  osskobot/src/assets/Wrong.png
  osskobot/src/components/Modal/ResultModal.js
  osskobot/src/components/Quiz/Question.js
  osskobot/src/screens/Logout.js
  osskobot/src/screens/Quiz.js
  osskobot/src/screens/QuizStyled.js
Labels: enhancement

#130 Feat: 마이페이지 스크린 CSS 적용
  osskobot/src/components/CommentBoard/CommentBoard.js
  osskobot/src/components/Modal/ProfileModifyModal.js
  osskobot/src/components/Modal/ProfileModifyModal.module.css
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
Labels: enhancement

#132 Feat: CheckModal CSS 적용
  osskobot/src/components/Modal/CheckModal.js
  osskobot/src/components/Modal/CheckModal.module.css
Labels: enhancement

#134 Feat: 도서 신청하기 css 적용
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Modal/BookRequestModal.js
  osskobot/src/components/Modal/BookRequestModal.module.css
  osskobot/src/components/Modal/BookRequestModalStyled.js
Labels: enhancement

#137 Feat: 대화하기 스크린 CSS 적용
  osskobot/src/components/ChatMsg/ChatMsg.js
  osskobot/src/components/ChatMsg/STTLoading.js
  osskobot/src/hooks/useInterval.js
  osskobot/src/screens/Chat.js
  osskobot/src/screens/Chat.module.css
  osskobot/src/screens/ChatCharChoose.js
  osskobot/src/screens/ChatStyled.js
Labels: enhancement

#139 Feat: 책 찜하기 기능 구현
  osskobot/src/components/Book/Book.js
  osskobot/src/components/CommentBoard/CommentBoard.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookClickStyled.js
  osskobot/src/screens/Home.js
Labels: enhancement

#141 Feat: 검색 기능 추가
  osskobot/src/App.js
  osskobot/src/components/Header/Header.js
  osskobot/src/screens/Home.js
Labels: enhancement

#144 Feat: 태그별 책 필터링 구현
  osskobot/src/components/Header/Header.js
  osskobot/src/screens/Home.js
Labels: enhancement

#146 Feat: 로그아웃 모달 구현
  osskobot/src/App.js
  osskobot/src/components/CommentBoard/CommentBoard.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Modal/CheckModal.js
  osskobot/src/screens/Logout.js
Labels: enhancement

#147 Feat: 로그인 스크린 CSS 적용
  osskobot/src/screens/Login.js
  osskobot/src/screens/Login.module.css
  osskobot/src/screens/LoginStyled.js
Labels: enhancement

#149 Feat: 회원가입 스크린 CSS 적용
  osskobot/src/screens/Join.js
  osskobot/src/screens/JoinStyled.js
  osskobot/src/screens/LoginStyled.js
Labels: enhancement

#151 Feat: 비밀번호 변경 페이지 위치 값 수정
  osskobot/src/screens/Find.js
Labels: bug, enhancement

#153 Feat: 책 상세 스크린 Info 추가
  osskobot/src/screens/BookClick.js
Labels: enhancement

#156 Feat: 검색 기능 수정
  osskobot/src/App.js
  osskobot/src/components/Book/Book.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Header/SubHeader.js
  osskobot/src/screens/Home.js
Labels: enhancement

#158 Feat: 내가 활동한 도서 기능 재구현
  osskobot/src/screens/Home.js
Labels: enhancement

#159 Feat: 홈 스크린 서브헤더 필터링 구현
  osskobot/src/App.js
  osskobot/src/assets/ErrorLogo.svg
  osskobot/src/components/Book/Book.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Header/SubHeader.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookReport.js
  osskobot/src/screens/Home.js
Labels: enhancement

#161 Feat: 홈 스크린 페이지네이션 구현
  osskobot/src/components/Footer/Footer.js
  osskobot/src/screens/BookClickStyled.js
  osskobot/src/screens/Home.js
Labels: enhancement

#164 Feat: 마이페이지 '나중에 읽을 책' 구현
  osskobot/src/screens/Home.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
Labels: enhancement

#166 Feat: 마이페이지 '작성한 독후감' 기능 구현
  osskobot/src/components/BookReport/BookReportInfo.js
  osskobot/src/components/Modal/BookReportModal.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
Labels: enhancement

#168 Feat: 마이페이지 '퀴즈 기록 보기' 구현
  osskobot/src/assets/Star.svg
  osskobot/src/assets/StarColor.svg
  osskobot/src/components/Quiz/QuizRecord.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
Labels: enhancement

#169 Feat: 제목순, 인기순 정렬 구현
  osskobot/src/components/Book/Book.js
  osskobot/src/components/SelectBox/SelectBox.js
  osskobot/src/screens/Home.js
  osskobot/src/services/refreshToken.js
Labels: enhancement

#171 Feat: 마이페이지 '이전 대화 내용 보기' 기능 구현
  osskobot/src/components/CharProfile/CharCard.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
Labels: enhancement

#173 Refactor: 북 컴포넌트 title 수정
  osskobot/src/components/Book/Book.js
  osskobot/src/screens/Home.js
Labels: enhancement

#175 Refactor: 코드 전체 리팩터링
  osskobot/src/components/Book/Book.js
  osskobot/src/components/CharProfile/CharCard.js
  osskobot/src/components/CharProfile/CharProfile.js
  osskobot/src/components/CharProfile/CharProfile.module.css
  osskobot/src/components/CommentBoard/CommentBoardStyled.js
  osskobot/src/components/CustomButton/BookClickBtn.js
  osskobot/src/components/CustomButton/BottomBorderBtn.js
  osskobot/src/components/CustomButton/CategoryBtn.js
  osskobot/src/components/Footer/Footer.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Header/SubHeader.js
  osskobot/src/components/Modal/BookReportModal.js
  osskobot/src/components/Modal/BookRequestModal.module.css
  osskobot/src/components/Modal/CharIntroModal.module.css
  osskobot/src/components/Modal/CheckModal.js
  osskobot/src/components/Modal/CheckModal.module.css
  osskobot/src/components/Modal/ProfileModifyModal.js
  osskobot/src/components/Modal/ProfileModifyModal.module.css
  osskobot/src/components/Modal/ResultModal.js
  osskobot/src/components/Profile/Profile.module.css
  osskobot/src/components/Quiz/Question.js
  osskobot/src/components/Quiz/QuizRecord.js
  osskobot/src/components/SelectBox/SelectBox.js
  osskobot/src/screens/BookClickStyled.js
  osskobot/src/screens/BookReport.js
  osskobot/src/screens/BookReportStyled.js
  osskobot/src/screens/Chat.js
  osskobot/src/screens/ChatCharChoose.js
  osskobot/src/screens/ChatCharChoose.module.css
  osskobot/src/screens/ChatStyled.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Home.module.css
  osskobot/src/screens/MypageStyled.js
  osskobot/src/screens/Quiz.js
  osskobot/src/screens/QuizStyled.js
  osskobot/src/screens/ServiceInfo.js
Labels: enhancement

#177 Feat: 데이터가 없는 도서 처리
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookClickStyled.js
Labels: enhancement

#179 Feat: Alert 커스텀 모달 구현
  osskobot/package-lock.json
  osskobot/package.json
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Modal/BookReportModal.js
  osskobot/src/components/Modal/BookRequestModal.js
  osskobot/src/components/Modal/BookRequestModalStyled.js
  osskobot/src/components/Modal/ProfileModifyModal.js
  osskobot/src/components/ProtectedRoute/ProtectedRoute.js
  osskobot/src/screens/BookReport.js
  osskobot/src/screens/Find.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Join.js
  osskobot/src/screens/Login.js
Labels: enhancement

#182 Feat: Header 수정 버전 구현
  osskobot/src/App.js
  osskobot/src/components/Header/Header.js
  osskobot/src/screens/WriteaBook.js
Labels: enhancement

#184 Feat: 마이페이지 '내가 쓴 책' 버튼 추가
  osskobot/package-lock.json
  osskobot/package.json
  osskobot/src/components/CharProfile/CharCard.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Modal/BookReportModal.js
  osskobot/src/components/Modal/BookRequestModal.js
  osskobot/src/components/Modal/BookRequestModalStyled.js
  osskobot/src/components/Modal/ProfileModifyModal.js
  osskobot/src/components/ProtectedRoute/ProtectedRoute.js
  osskobot/src/components/Quiz/QuizRecord.js
  osskobot/src/screens/BookReport.js
  osskobot/src/screens/Find.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Join.js
  osskobot/src/screens/Login.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
Labels: enhancement

#186 Feat: 회원탈퇴하기 기능 구현
  osskobot/src/App.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
Labels: enhancement

#189 Feat: 책 표지에 이름 넣기
  osskobot/src/components/Book/SizeBook.js
  osskobot/src/components/Header/ChatHeader.js
  osskobot/src/screens/BookClick.js
  osskobot/src/screens/BookClickStyled.js
Labels: enhancement

#191 Refactor: 코드 전체 리팩터링 2
  osskobot/src/components/Modal/BookReportModal.js
  osskobot/src/components/Modal/BookRequestModal.js
  osskobot/src/components/Modal/BookRequestModal.module.css
  osskobot/src/components/Modal/BookRequestModalStyled.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Join.js
  osskobot/src/screens/Join.module.css
  osskobot/src/screens/JoinStyled.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/MypageStyled.js
  osskobot/src/screens/Quiz.js
Labels: enhancement

#192 Feat: 내가 작가 되어보기 페이지 수정
  osskobot/src/App.js
  osskobot/src/assets/mp3/little_boy.mp3
  osskobot/src/assets/mp3/little_girl.mp3
  osskobot/src/assets/mp3/man_adult.mp3
  osskobot/src/assets/mp3/man_old.mp3
  osskobot/src/assets/mp3/woman_adult.mp3
  osskobot/src/assets/mp3/woman_old.mp3
  osskobot/src/components/CharProfile/CharCard.js
  osskobot/src/components/Header/Header.js
  osskobot/src/components/Modal/CharSelectModal.js
  osskobot/src/components/Quiz/QuizRecord.js
  osskobot/src/screens/Home.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/WriteaBook.js
Labels: enhancement

#194 Feat: 마이페이지 '내가 쓴 책' 구현
  osskobot/src/App.js
  osskobot/src/components/Book/Book.js
  osskobot/src/screens/BookClickStyled.js
  osskobot/src/screens/MyBookClick.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/WriteaBook.js
Labels: enhancement

#196 Feat: 내가 쓴 책 대화하기 기능 구현
  osskobot/src/components/Book/Book.js
  osskobot/src/components/CharProfile/CharProfile.js
  osskobot/src/components/CustomButton/BookClickBtn.js
  osskobot/src/screens/Chat.js
  osskobot/src/screens/ChatCharChoose.js
  osskobot/src/screens/MyBookClick.js
  osskobot/src/screens/Mypage.js
  osskobot/src/screens/WriteaBook.js
Labels: enhancement
